"""filing report_date replaces fiscal_period

Revision ID: 8e8757e0ec19
Revises: 597bd0688fb4
Create Date: 2026-06-17 18:47:57.932939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8757e0ec19'
down_revision: Union[str, Sequence[str], None] = '597bd0688fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('report_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_filings_report_date'), 'filings', ['report_date'], unique=False)
    op.drop_column('filings', 'fiscal_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('fiscal_period', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_filings_report_date'), table_name='filings')
    op.drop_column('filings', 'report_date')
    # ### end Alembic commands ###
