"""user role + encrypted rh tokens

Revision ID: dc5f45ab4851
Revises: f4d5e6a7b8c9
Create Date: 2026-06-30 11:42:04.623343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5f45ab4851'
down_revision: Union[str, Sequence[str], None] = 'f4d5e6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('users', sa.Column('robinhood_linked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('rh_access_token_enc', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('rh_refresh_token_enc', sa.Text(), nullable=True))
    op.alter_column('users', 'clerk_user_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.drop_column('users', 'robinhood_token_enc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('robinhood_token_enc', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'clerk_user_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'rh_refresh_token_enc')
    op.drop_column('users', 'rh_access_token_enc')
    op.drop_column('users', 'robinhood_linked')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
